dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: lKycUd9bTmtCmCIT7Mx0yG/4v0H27zuRdfhp1DGtXqKKIuKZB3BMQ+nMRnHo9FC7jwM8NOHriWn9m/bYwQbhSgNersJUboDznZtw6O5oASfyqOP2qSfcJj1JE0sPj2BTK7kwRgjPUscCBuuzloi3pdDkoNNSwCI2BXOgRYQ9GQIT0pNf7T55BZ/sIDBAFjqH7oi7jf/qNnmwlZz6nvV6txnA0e8cv6AoUdpfsaAnEt8vEj5FOOygPqNqTHZgIViPyBZwCTerqNmFB3fdtj+BtrC0OkA/3eMLx+DTf0GFNeQC4LIWeU7+AqbLlm4cdkSKMvvpx02hkb8nAIA5Js1yGLL7SLISp+4X2g/NKPdwpEwnWFl1tI0Ijuh+uLGUrq1fy5FwdK/PjGa5iC6YzDJUYEjLh3zr/O7MkE9et1FIsEz7JUGR03lo/FLW3MLZa3muQiunPHcANdf1BdHrQVM1GmP+OxteeRFqBXff4D1UjHjRQUHdCt161c/9Y0DBIYPKgXVcj2CFgvYqKfcjuUsA76f4dDdfnIHXlpWpUc9oL1WfJHJA1s0UJenWzDWwVCH9sSZdoyHPQObXTFfEke9FYNcT5gVge8kwngAZo+/EvBxk34tqkGooastICEV/WotX4+knUiCac2DZjWiGEzFz5t+b2OgYvaPmeLA0Ml3a1G0=
