dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash
notifications:
  slack:
    secure: HrFz+HDmFN9FbYDf6UxPm4LdD9nwMO7wUIsBF/aVFnlHRWORzQYXR+zZWMjIZzZXPfaD6boXlq2vyVgUnEOaAxID5wWfwLh9+EGUCGgWpdZqB6Hbn7Ro/d1bhLYVUtn/TiSEobirBb4KLNTFdHNL9tSEaYsNslS0/pfT7PzTzYpY9HRNYVHycpCsLg4HDnjrODzIlAxqTmWlHONqo0aUII9p+b5IhQ3N+vDowKauyofzpZiaPTmR2Zcyxy1LipK7QP9DnPrfOPr7z5n9X/UnpLPNlDXtQvdZI2nY30oguZRHvsmLUbnLcxRsJudKTZDUXsZvkMXLQ6R2IgmXavwVLYrzMRXO3Rx+uZxaTN22Ok486wv79kT8ggdTjoqyPczpmm6zRXC5fylstUXio6NEggnula74EpDkBpMYlKzO5KaJMdCzdnpX5p7hueCmLRE6IUrTY4IyOnFOzgqC6ZpylIhiCTsxFYvgh9HxFDIpm0+eiXcNqEWk5+dbJmNaZBSv3Xnz+NzqcZyo8JDaR8fq7az+yxpiEeHe6A5SW8OOpbqOjsSGWGX0OtWs6PVmTSZZoezvkHMFHwoXsLqXp5GAFrsXNZ72GA6HukiJ3Ej87rVvPGpfG2M/MF4SUZWKN/dkRsAyTJcsQhp5Z4bvja4ANrdNlLmNnAoUh7E40ZFjB6I=
