dist: trusty

sudo: required

language: bash

jobs:
  include:
    - stage: test_packer
      install:
        - sudo apt-get install ansible
        - curl -L -o packer.zip https://releases.hashicorp.com/packer/1.5.5/packer_1.5.5_linux_amd64.zip
        - unzip -d bin packer.zip
        - export PATH="$(pwd)/bin:$PATH"
      script:
        - packer validate -var-file=packer/variables.json.example packer/app.json
        - packer validate -var-file=packer/variables.json.example packer/db.json
    - stage: test_terraform
      install:
        - curl -L -o terraform.zip https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
        - unzip -d bin terraform.zip
        - export PATH="$(pwd)/bin:$PATH"
      script:
        - cd terraform
        - terraform get stage
        - terraform get prod
        - terraform validate stage
        - terraform validate prod
        - terraform init -backend=false stage
        - terraform init -backend=false prod
    - stage: test_ansible
      install:
        - pip install ansible-lint
      script:
        - find ansible/playbooks -type f -name '*.yml' -print0 | ansible-lint --exclude=roles/jdauphant.nginx
    - stage: test_otus
      before_install:
        - curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
          bash

notifications:
  slack:
    rooms:
      secure: hQTYZRgtBlpXY56epbEAL5ZLO70MzTSH1RHYglhSG7XQLWKg8x+qCzjp4ykD1scj769HBYVmI6zKl9aQxEwt/rUi3GGnjr1P7wuj4doWGLPhA3xpqZd3z3oPFxBoBOtUkAYglQxcCYFVZ7VGmK4xYirI0BlNHDkYgsTCOCYDeVjVV1Pi+SN/Q9/2zVnlOJ5nCj1tyXwt4ctfatAkAPCVNllrf/5XL28XgQZcZJqrsyEG2wXvDflzDIv/0eySOaWZ2dPRYt39997NEIZt7pPQTlVw2CRB2UPqk8nn+RVPL1SRZtue0vIQNNpMdtT4JoZ0COeZarDR/vYIVvNHilSun6HeEAuRZJ4GjOyjs+RZGpTQENF/s0kW2zPpq7uGB40EgWKDC0KEPeanIDSB7XMQUIQiXfaEqOXGaoasEPIp08gIdaEwoIMSJmloDSJZxKOeP/ATkFVDeZ0UOOT/i8GAtQbe+HEQZVi1OxEx5wMlNNAxuiyzzgnw5ATIOhPIN+nflX1CsBoolPA/XBpH59w2xboMrwdrr+V4DxFsYFPHsaPBcr8TPEqhSZWlvUxRPtEKJ21B8XXRAFB2S89MXR/tAQn8P2fGoqblcneW2cZIv3HadU3Er5ntynRsaGigcuDKt8h3gYELKiowzM30cxpwIzjZhpet686/AqBuCyCszks=
