---
# tasks file for app

- name: "Add unit file for Puma"
  become: true
  copy:
    src: "files/puma.service"
    dest: "/etc/systemd/system/puma.service"
  notify: "reload puma"

- name: "Add config for DB connection"
  template:
    src: "templates/db_config.j2"
    dest: "/home/den_pirozhkov/db_config"

- name: "Enable puma"
  become: true
  systemd:
    name: puma
    enabled: yes
