---

- name: "Install Ruby and Byndler"

  hosts: all

  become: true

  tasks:

  - name: "install pkgs"
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - ruby-full
      - ruby-bundler
      - build-essential
